//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tett.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int MaTT { get; set; }
        public int SoHD { get; set; }
        public Nullable<double> PhiPS { get; set; }
        public string LyDo { get; set; }
        public int MaUser { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual User User { get; set; }
    }
}
