//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tett.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testDBEntities : DbContext
    {
        public testDBEntities()
            : base("name=testDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHopDong> ChiTietHopDongs { get; set; }
        public virtual DbSet<DatXe> DatXes { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<XeRa> XeRas { get; set; }
        public virtual DbSet<XeVao> XeVaos { get; set; }
        public virtual DbSet<YeuCau> YeuCaus { get; set; }
        public virtual DbSet<SoDatXe> SoDatXes { get; set; }
        public virtual DbSet<ThamSo> ThamSoes { get; set; }
    }
}
